#!/usr/bin/env python3
"""Generate port/EmojiStills.codex and port/CatStills.codex from the game's
baked tables.

STILLS, NOT FRAMES. The game's file is called emoji_frames.zig and "frames" reads
like animation frames, which these emphatically are not: it is ONE still per
species, eight of them, 129 polygons in all, and the animals never animate -- they
are static billboards that scale with distance. Every bit of motion in this port is
computed per frame, not looked up. The port takes the better name wherever a name
is not pinned by a seam check; where it IS pinned, fidelity wins.

GENERATED, NOT HAND-PORTED, and that is NOTES section 5's own prescription: the
art is 182 KB produced by ops/bake_emoji running vendored SVG through a recorder,
so hand-carrying it into Codex would be the wrong shape of work and would rot the
moment the baker ran again. This converts what the baker already emitted.

The chapter is TRACKED like the gold chapters are, and regenerated by this script
rather than edited. Run it if emoji_frames.zig ever changes.

WHY IT FITS. PORTING_NOTES C7 records that codexzig exhausts its 4 GiB bump heap
on a single Real literal of about 16,868 elements. The whole emoji table is 5,267
points -- 10,534 Reals -- and no single polygon is anywhere near the ceiling,
because each polygon's point list is its own literal. The cat's table is bigger
(26,906 Reals) and would want splitting per pose.

GRADIENTS ARE FLATTENED TO THEIR FIRST STOP, and it affects exactly one species.
Seven of the eight are the Fluent FLAT art and are solid throughout; only the bull
is the Color variant, with 40 of its 43 polygons carrying a 2-stop linear or
radial gradient. paint.zig has wire tags for those (5 and 6) and Safari chapter
Paint does not model them yet, so the bull draws flat. Every other animal is
exact. Critter.codex says so where it matters.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EMOJI = ROOT / "probe" / "wasm" / "emoji_frames.zig"
CAT = ROOT / "probe" / "wasm" / "cat_frames.zig"

# BOTH TABLES, ONE SCRIPT, because bake_emoji and bake_cat emit the same shape --
# named arrays of solid polygons in the same unit frame -- and the only real
# difference is what the lookup is keyed on: a codepoint for the animals, a pose
# index for the cat. Two scripts would have restated poly_arrays and the literal
# formatting, which is the drift this repo already learned to avoid.
POSE_NAMES = ["pose_rest", "pose_stride", "pose_frozen", "pose_coil",
              "pose_flight", "pose_land", "pose_collapse"]


def poly_arrays(text):
    named = {}
    for m in re.finditer(r"const (\w+) = \[_\]Poly\{(.*?)\n\};", text, re.S):
        polys = []
        for pm in re.finditer(r"\.color = 0x([0-9A-Fa-f]+).*?\.pts = &\[_\]Pt\{(.*?)\} \}",
                              m.group(2), re.S):
            pts = [(float(a), float(b)) for a, b in
                   re.findall(r"\.x = (-?[\d.e-]+), \.y = (-?[\d.e-]+)", pm.group(2))]
            if len(pts) >= 3:
                polys.append((int(pm.group(1), 16), pts))
        if polys:
            named[m.group(1)] = polys
    return named


def real(v):
    """Codex wants a decimal point on every Real, and a negative literal is written
    as a subtraction because the grammar has no unary minus in a list element."""
    s = f"{v:.6g}"
    if "e" in s or "E" in s:
        s = f"{v:.10f}".rstrip("0").rstrip(".") or "0"
    if "." not in s:
        s += ".0"
    return f"(0.0 - {s[1:]})" if s.startswith("-") else s


def chapter(name, head, sections, lookup):
    """Assemble one stills chapter: a shared shape section, one section per still,
    and the lookup that selects between them."""
    # THE SHAPES LIVE IN THEIR OWN CHAPTER, cited by both. Codex chapters share ONE
    # FLAT NAMESPACE inside a bundle (PORTING_NOTES B5), so two generated tables
    # each defining StillPt would collide the moment anything cited both -- which
    # render does, since it draws animals and a cat in the same frame.
    out = [f"Chapter: {name}", "  cites Safari chapter Stills", ""] + head + [
        "", " We say:", "",
    ]
    for title, binding, polys in sections:
        n = sum(len(p) for _, p in polys)
        out += [f"Section: {title}", "", f" {len(polys)} polygons, {n} points.", "",
                f"  {binding} : List StillPoly", f"  {binding} ="]
        # ONE LINE FOR THE WHOLE LIST. A Codex list literal may not span a newline
        # any more than an application may (PORTING_NOTES B1/C12) -- broken across
        # lines it halts with CDX1025 "Unclosed list literal".
        rows = []
        for color, pts in polys:
            body = ", ".join(f"StillPt {{ x = {real(x)}, y = {real(y)} }}" for x, y in pts)
            rows.append(f"StillPoly {{ color = {color}, pts = [{body}] }}")
        out += ["    [" + ", ".join(rows) + "]", ""]
    return "\n".join(out + lookup + [""])


SHAPES = """Chapter: Stills

 The shape a baked still is made of, shared by every generated table.

 IT IS ITS OWN CHAPTER FOR A NAMESPACE REASON. Codex chapters share one flat
 namespace inside a bundle (PORTING_NOTES B5), so EmojiStills and CatStills cannot
 each define these -- render draws animals and a cat in the same frame and cites
 both. Hand-written, unlike the tables that cite it, because it never changes.

 A point is in the UNIT FRAME the billboards use: feet at y = 0, y up, height 1,
 facing LEFT. A polygon is solid; the one gradient in the game's art is flattened
 by the baker, and Safari chapter Critter says which animal that costs.

 We say:

Section: Shapes

  StillPt = record {
    x : Real,
    y : Real
  }

  StillPoly = record {
    color : Integer,
    pts : List StillPt
  }
"""


def main():
    (ROOT / "port" / "Stills.codex").write_text(SHAPES)
    print("port/Stills.codex  (shared shapes, hand-written)")
    text = EMOJI.read_text()
    named = poly_arrays(text)
    order = [(int(m.group(1), 16), m.group(2))
             for m in re.finditer(r"0x0([0-9A-F]{5}) => &(\w+),", text)]
    write_emoji(named, order)
    write_cat()
    return 0


def write_emoji(named, order):
    head = [
        " GENERATED by harness/bake_stills.py from wasm/emoji_frames.zig.",
        " Do not edit: re-run the script instead.",
        "",
        " The roadside animals as polygon STILLS -- one per species, and they do not",
        " animate at all -- in the unit frame the billboards use: feet at y = 0, y up,",
        " height 1, facing LEFT. Safari chapter Critter looks one up by codepoint and",
        " transforms it to a screen anchor.",
        "",
        " GRADIENTS ARE FLATTENED TO THEIR FIRST STOP and it affects one species. Seven",
        " of the eight are the Fluent Flat art and are solid throughout; only the bull",
        " is the Color variant, with 40 of its 43 polygons carrying a 2-stop gradient.",
        " paint.zig has wire tags for those and Safari chapter Paint does not model them",
        " yet, so the bull draws flat and every other animal is exact.",
    ]
    sections = [(name.capitalize(), f"{name}-polys", named.get(name, [])) for _, name in order]
    arms = "\n    else ".join(f"if cp == {cp} then {name}-polys" for cp, name in order)
    lookup = ["Section: Lookup", "",
              " By codepoint, in emoji_frames.zig's own switch order. An unknown codepoint",
              " draws nothing, which is what `orelse return` does in the zig.", "",
              "  emoji-polys-for : Integer -> List StillPoly",
              "  emoji-polys-for (cp) =",
              "    " + arms + "\n    else []"]
    text_out = chapter("EmojiStills", head, sections, lookup)
    dst = ROOT / "port" / "EmojiStills.codex"
    dst.write_text(text_out)
    total = sum(sum(len(p) for _, p in named.get(n, [])) for _, n in order)
    print(f"port/EmojiStills.codex  ({len(order)} species, {total} points, "
          f"{dst.stat().st_size // 1024} KB)")


def write_cat():
    """The cat's flipbook: SEVEN stills, not seven hundred. cat.zig picks one per
    crossing step and computes the position continuously; nothing here is an
    animation frame."""
    named = poly_arrays(CAT.read_text())
    head = [
        " GENERATED by harness/bake_stills.py from wasm/cat_frames.zig.",
        " Do not edit: re-run the script instead.",
        "",
        " The crossing cat as a FLIPBOOK of seven named stills -- rest, stride, frozen,",
        " coil, flight, land, collapse -- in the unit frame the billboards use: feet at",
        " y = 0, y up, standing height 1, x toward the tail, facing LEFT.",
        "",
        " SEVEN STILLS, NOT SEVEN HUNDRED. Safari chapter Cat's `cat-state` picks which",
        " one per crossing step and computes the lateral travel and the hop continuously,",
        " so the animation is COMPUTED and only the shapes are looked up. cat_anatomy's",
        " fills are baked as polygons and its strokes as thin quads; all are solid, so",
        " unlike the animals nothing here is flattened.",
    ]
    sections = [(n.replace("pose_", "").capitalize(), n.replace("_", "-") + "-polys",
                 named[n]) for n in POSE_NAMES if n in named]
    arms = "\n    else ".join(
        f"if i == {k} then {n.replace('_', '-')}-polys" for k, n in enumerate(POSE_NAMES))
    lookup = ["Section: Lookup", "",
              " By pose index, which is what cat-state returns. An index outside the",
              " flipbook draws nothing.", "",
              "  cat-polys-for : Integer -> List StillPoly",
              "  cat-polys-for (i) =",
              "    " + arms + "\n    else []"]
    dst = ROOT / "port" / "CatStills.codex"
    dst.write_text(chapter("CatStills", head, sections, lookup))
    total = sum(len(p) for n in POSE_NAMES for _, p in named.get(n, []))
    print(f"port/CatStills.codex  ({len(sections)} poses, {total} points, "
          f"{dst.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    sys.exit(main())
