#!/usr/bin/env python3
"""Generate port/EmojiStills.codex from the game's baked emoji_frames.zig.

STILLS, NOT FRAMES. The game's file is called emoji_frames.zig and "frames" reads
like animation frames, which these emphatically are not: it is ONE still per
species, eight of them, 129 polygons in all, and the animals never animate -- they
are static billboards that scale with distance. Every bit of motion in this port is
computed per frame, not looked up. The port takes the better name wherever a name
is not pinned by a seam check; where it IS pinned, fidelity wins.

GENERATED, NOT HAND-PORTED, and that is NOTES section 5's own prescription: the
art is 182 KB produced by ops/bake_emoji running vendored SVG through a recorder,
so hand-carrying it into Codex would be the wrong shape of work and would rot the
moment the baker ran again. This converts what the baker already emitted.

The chapter is TRACKED like the gold chapters are, and regenerated by this script
rather than edited. Run it if emoji_frames.zig ever changes.

WHY IT FITS. PORTING_NOTES C7 records that codexzig exhausts its 4 GiB bump heap
on a single Real literal of about 16,868 elements. The whole emoji table is 5,267
points -- 10,534 Reals -- and no single polygon is anywhere near the ceiling,
because each polygon's point list is its own literal. The cat's table is bigger
(26,906 Reals) and would want splitting per pose.

GRADIENTS ARE FLATTENED TO THEIR FIRST STOP, and it affects exactly one species.
Seven of the eight are the Fluent FLAT art and are solid throughout; only the bull
is the Color variant, with 40 of its 43 polygons carrying a 2-stop linear or
radial gradient. paint.zig has wire tags for those (5 and 6) and Safari chapter
Paint does not model them yet, so the bull draws flat. Every other animal is
exact. Critter.codex says so where it matters.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "probe" / "wasm" / "emoji_frames.zig"


def poly_arrays(text):
    named = {}
    for m in re.finditer(r"const (\w+) = \[_\]Poly\{(.*?)\n\};", text, re.S):
        polys = []
        for pm in re.finditer(r"\.color = 0x([0-9A-Fa-f]+).*?\.pts = &\[_\]Pt\{(.*?)\} \}",
                              m.group(2), re.S):
            pts = [(float(a), float(b)) for a, b in
                   re.findall(r"\.x = (-?[\d.e-]+), \.y = (-?[\d.e-]+)", pm.group(2))]
            if len(pts) >= 3:
                polys.append((int(pm.group(1), 16), pts))
        if polys:
            named[m.group(1)] = polys
    return named


def real(v):
    """Codex wants a decimal point on every Real, and a negative literal is written
    as a subtraction because the grammar has no unary minus in a list element."""
    s = f"{v:.6g}"
    if "e" in s or "E" in s:
        s = f"{v:.10f}".rstrip("0").rstrip(".") or "0"
    if "." not in s:
        s += ".0"
    return f"(0.0 - {s[1:]})" if s.startswith("-") else s


def main():
    text = SRC.read_text()
    named = poly_arrays(text)
    order = [(int(m.group(1), 16), m.group(2))
             for m in re.finditer(r"0x0([0-9A-F]{5}) => &(\w+),", text)]
    out = [
        "Chapter: EmojiStills", "",
        " GENERATED by harness/bake_emoji_stills.py from wasm/emoji_frames.zig.",
        " Do not edit: re-run the script instead.",
        "",
        " The roadside animals as polygon stills in the UNIT FRAME the billboards use",
        " -- feet at y = 0, y up, height 1, facing LEFT. Safari chapter Critter looks",
        " one up by codepoint and transforms it to a screen anchor.",
        "",
        " GRADIENTS ARE FLATTENED TO THEIR FIRST STOP and it affects one species. Seven",
        " of the eight are the Fluent Flat art and are solid throughout; only the bull",
        " is the Color variant, with 40 of its 43 polygons carrying a 2-stop gradient.",
        " paint.zig has wire tags for those and Safari chapter Paint does not model them",
        " yet, so the bull draws flat and every other animal is exact.",
        "", " We say:", "", "Section: Shapes", "",
        "  EmojiPt = record {", "    x : Real,", "    y : Real", "  }", "",
        "  EmojiPoly = record {", "    color : Integer,", "    pts : List EmojiPt", "  }", "",
    ]
    for cp, name in order:
        polys = named.get(name, [])
        n = sum(len(p) for _, p in polys)
        out += [f"Section: {name.capitalize()}", "",
                f" {len(polys)} polygons, {n} points.", "",
                f"  {name}-polys : List EmojiPoly", f"  {name}-polys ="]
        # ONE LINE FOR THE WHOLE LIST. A Codex list literal may not span a
        # newline any more than an application may (PORTING_NOTES B1) -- broken
        # across lines it halts with CDX1025 "Unclosed list literal". The bull's
        # line runs to about 200 KB, which is fine in a file and is why this is
        # generated rather than typed.
        rows = []
        for color, pts in polys:
            body = ", ".join(f"EmojiPt {{ x = {real(x)}, y = {real(y)} }}" for x, y in pts)
            rows.append(f"EmojiPoly {{ color = {color}, pts = [{body}] }}")
        out.append("    [" + ", ".join(rows) + "]")
        out.append("")
    out += ["Section: Lookup", "",
            " By codepoint, in emoji_frames.zig's own switch order. An unknown codepoint",
            " draws nothing, which is what `orelse return` does in the zig.", "",
            "  emoji-polys-for : Integer -> List EmojiPoly",
            "  emoji-polys-for (cp) ="]
    arms = [f"    if cp == {cp} then {name}-polys" for cp, name in order]
    body = "\n    else ".join(a.strip() for a in arms)
    out.append("    " + body + "\n    else []")
    out.append("")
    dst = ROOT / "port" / "EmojiStills.codex"
    dst.write_text("\n".join(out))
    total = sum(sum(len(p) for _, p in named.get(n, [])) for _, n in order)
    print(f"port/EmojiStills.codex  ({len(order)} species, {total} points, "
          f"{dst.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
