// Generate gold/BlitGold.codex from web/blitter.js.
//
//   node harness/gen_blit_gold.js > gold/BlitGold.codex
//
// THE ORACLE HERE IS JAVASCRIPT. Every other gold in this repository comes from
// importing a real zig game module; these numbers come from the browser half,
// because the browser half is where the shading recipe and the visibility
// thresholds actually live. It is the same arrangement and the same rule: the
// oracle is the thing that is authoritative today, and it is imported rather
// than transcribed.
//
// The INPUT tables are printed too, and the check maps over those, so there is
// exactly one copy of every input rather than two kept in step by hand.

const src = require('fs').readFileSync(__dirname + '/../web/blitter.js', 'utf8');
// Lift the port candidates out of the blitter without loading it: it is a browser
// module and touches `document` at the bottom. Taking the functions by name means
// a rename here fails loudly rather than silently grading a stale copy.
const WANTED = ['shadeColor', 'widthShadeStops', 'discIsVisible', 'radialIsVisible', 'tooNarrowToShade'];
const CONSTS = ['SHADE_EDGE_DARKEN', 'SHADE_MIDDLE_LIFT', 'MIN_DISC_RADIUS', 'MIN_DISC_ALPHA',
                'MIN_GRADIENT_RADIUS', 'MIN_SHADE_WIDTH'];
let lifted = '';
for (const name of CONSTS) {
  const m = src.match(new RegExp(`^const ${name} = [^;]+;`, 'm'));
  if (!m) throw new Error(`blitter.js no longer defines ${name}`);
  lifted += m[0] + '\n';
}
for (const name of WANTED) {
  const at = src.indexOf(`function ${name}(`);
  if (at < 0) throw new Error(`blitter.js no longer defines ${name}`);
  // to the matching closing brace at column 0, or the end of a one-liner
  const nl = src.indexOf('\n', at);
  const oneLine = src.slice(at, nl).trimEnd().endsWith('}');
  const end = oneLine ? nl : src.indexOf('\n}\n', at) + 3;
  lifted += src.slice(at, end) + '\n';
}
const F = new Function(lifted + `return {${WANTED.join(',')}};`)();

const COLORS = [0x000000, 0x010203, 0x4a8f43, 0x7f7f7f, 0x808080, 0xc0ffee,
                0xff0000, 0x00ff00, 0x0000ff, 0xfedcba, 0xffffff];
const FACTORS = [0.0, 0.25, 0.6, 0.75, 1.0, 1.25, 1.6, 2.0, 4.0];
const STRENGTHS = [0.0, 0.01, 0.25, 0.5, 0.75, 1.0];
const RADII = [0.0, 0.1, 0.49, 0.5, 0.51, 1.0, 40.0];
const ALPHAS = [0.0, 0.01, 0.019, 0.02, 0.021, 0.5, 1.0];
const WIDTHS = [[0, 0], [0, 0.5], [0, 0.999], [0, 1], [0, 1.5], [10, 10.5], [10, 40]];

const reals = (xs) => '[' + xs.map((x) => (Number.isInteger(x) ? x.toFixed(1) : String(x))).join(', ') + ']';
const ints = (xs) => '[' + xs.join(', ') + ']';
const bools = (xs) => '[' + xs.map((b) => (b ? 'True' : 'False')).join(', ') + ']';

const shadeIn = [], shadeF = [], shadeOut = [];
for (const c of COLORS) for (const f of FACTORS) { shadeIn.push(c); shadeF.push(f); shadeOut.push(F.shadeColor(c, f)); }

const crownC = [], crownS = [], crownOut = [];
for (const c of COLORS) for (const s of STRENGTHS) {
  crownC.push(c); crownS.push(s);
  for (const [, col] of F.widthShadeStops(c, s)) crownOut.push(col);
}

const discR = [], discA = [], discOut = [];
for (const r of RADII) for (const a of ALPHAS) { discR.push(r); discA.push(a); discOut.push(F.discIsVisible(r, a)); }

const out = [];
out.push('Chapter: BlitGold', '');
out.push(' GENERATED by harness/gen_blit_gold.js from web/blitter.js.');
out.push(' Every value here came from the browser half of the renderer, unmodified.');
out.push(' Do not edit: the next harness run overwrites this file.', '');
out.push(' We say:', '', 'Section: Gold', '');
out.push(`  g-blit-shade-c : List Integer`, `  g-blit-shade-c = ${ints(shadeIn)}`, '');
out.push(`  g-blit-shade-f : List Real`, `  g-blit-shade-f = ${reals(shadeF)}`, '');
out.push(`  g-blit-shade : List Integer`, `  g-blit-shade = ${ints(shadeOut)}`, '');
out.push(`  g-blit-crown-c : List Integer`, `  g-blit-crown-c = ${ints(crownC)}`, '');
out.push(`  g-blit-crown-s : List Real`, `  g-blit-crown-s = ${reals(crownS)}`, '');
out.push(`  g-blit-crown : List Integer`, `  g-blit-crown = ${ints(crownOut)}`, '');
out.push(`  g-blit-disc-r : List Real`, `  g-blit-disc-r = ${reals(discR)}`, '');
out.push(`  g-blit-disc-a : List Real`, `  g-blit-disc-a = ${reals(discA)}`, '');
out.push(`  g-blit-disc : List Boolean`, `  g-blit-disc = ${bools(discOut)}`, '');
out.push(`  g-blit-radial-r : List Real`, `  g-blit-radial-r = ${reals(RADII)}`, '');
out.push(`  g-blit-radial : List Boolean`, `  g-blit-radial = ${bools(RADII.map(F.radialIsVisible))}`, '');
out.push(`  g-blit-width-lo : List Real`, `  g-blit-width-lo = ${reals(WIDTHS.map((w) => w[0]))}`, '');
out.push(`  g-blit-width-hi : List Real`, `  g-blit-width-hi = ${reals(WIDTHS.map((w) => w[1]))}`, '');
out.push(`  g-blit-flat : List Boolean`, `  g-blit-flat = ${bools(WIDTHS.map(([a, b]) => F.tooNarrowToShade(a, b)))}`, '');
out.push('Page 1', '');
process.stdout.write(out.join('\n'));
