#!/usr/bin/env python3
"""Build a module's zig probe, run it, and write its answers as a Codex chapter.

The gold is REGENERATED from the hand-written zig on every run rather than
checked in. A checked-in gold file is a second copy of the oracle, and a second
copy is a thing that can quietly disagree with the first -- which is the failure
this port exists to detect, so it must not be possible to introduce it here.

Takes the CHAPTER name -- `Pond`, `GuardRail` -- and derives the rest, so a
module is named once. The probe is snake_case, matching the game file it imports
(`GuardRail` -> `probe/probe_guard_rail.zig`, beside `wasm/guard_rail.zig`); the
gold chapter is the name with `Gold` appended.

Reads `<kind> <name> <values...>` lines from the probe (kinds R, I, B; see
probe/probe_pond.zig) and emits one Codex binding per line, named `g-<name>`.

Real literals: zig's {d} prints the shortest round-tripping form, so `3` and
`0.9` arrive as text that already carries the f32 exactly. Codex wants a decimal
point on every Real, and exponent forms are expanded rather than passed through,
because a literal is the one place a port cannot afford a parse it has not seen.
A value needing more than an i64's worth of digits is REFUSED rather than written;
see real_literal.
"""

import decimal
import pathlib
import subprocess
import sys

from names import snake

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
ZIG = pathlib.Path.home() / 'zig-0.16.0' / 'zig'


# THE PARSER BEHIND THIS LIMIT, and it is not a style rule. Codex builds a Real
# literal by accumulating EVERY digit from the first significant one to the last
# into a 64-bit integer and then dividing by a power of ten -- and that
# accumulation wraps silently, because the zig plug emits `*%` for a multiply the
# language declares as checked (FINDINGS.md item 1). Past i64 the literal becomes
# a different number, usually a NEGATIVE one, with no diagnostic anywhere: written
# out in full, 1e18 reaches the compiler as -8.4467e17. The value is folded in the
# front end and reaches the emitter as a bit pattern, so no plug can see it.
#
# A GOLD FILE IS THE ORACLE, so a value it cannot carry must stop the run rather
# than be written. This is the one place that can tell -- by the time a check is
# red, the literal looks like a disagreement in the port.
I64_MAX = 2 ** 63 - 1


def real_literal(tok):
    """A Codex Real literal for one token of zig {d} output."""
    if 'e' in tok or 'E' in tok:
        tok = format(decimal.Decimal(tok), 'f')
    lit = tok if '.' in tok else tok + '.0'
    digits = lit.lstrip('-').replace('.', '').lstrip('0')
    if digits and int(digits) > I64_MAX:
        raise SystemExit(
            f'gold value {tok} needs {len(digits)} significant digits; Codex parses '
            f'a Real literal through a wrapping i64 and would read it as a different '
            f'number. Narrow the probe\'s domain, or scale the value it prints.')
    return lit


def build_and_run(chapter):
    """Compile the probe beside its source, so the wasm/ symlink resolves."""
    probe = ROOT / 'probe'
    src = f'probe_{snake(chapter)}.zig'
    if not (probe / src).is_file():
        raise SystemExit(f'no probe/{src}')
    # DEBUG. There is no optimisation level that makes this binary "the" oracle, so
    # it may as well be the cheap one -- see PORTING_NOTES C9. The game ships TWICE,
    # at two levels on two targets: the browser wasm at -O ReleaseSmall and the
    # native screensaver at ReleaseFast. A native ReleaseFast probe matches neither
    # authoritatively, so this is a REFERENCE computation of the game's algorithm,
    # and what makes the port trustworthy is the calibrated tolerance, not the last
    # bit of one build. Measured: the level moves exactly one value in the whole
    # port, sky's sun_x, by about 36 ulps, and the check is green either way.
    # zig does not cache this -- a warm rebuild of an unchanged probe was 28 s
    # against a 22 s cold one -- so ReleaseFast was 25 s per module on EVERY sweep.
    subprocess.run([str(ZIG), 'build-exe', src], cwd=probe, check=True)
    # The probes write to stderr: zig 0.16 removed std.io.getStdOut() and
    # std.debug.print is what the rest of this harness uses.
    out = subprocess.run([f'./probe_{snake(chapter)}'], cwd=probe,
                         capture_output=True, text=True, check=True)
    return out.stderr


def gold_chapter(chapter, gold_text):
    name = chapter + 'Gold'
    lines = [f'Chapter: {name}', '',
             f' GENERATED by harness/gen_gold.py from probe/probe_{snake(chapter)}.zig.',
             ' Every value here came from importing the real game module unmodified.',
             ' Do not edit: the next harness run overwrites this file.', '',
             ' We say:', '', 'Section: Gold', '']
    for raw in gold_text.splitlines():
        if not raw.strip():
            continue
        kind, nm, *vals = raw.split()
        if kind == 'R':
            ty, items = 'List Real', [real_literal(v) for v in vals]
        elif kind == 'I':
            ty, items = 'List Integer', vals
        elif kind == 'B':
            ty, items = 'List Boolean', ['True' if v == '1' else 'False' for v in vals]
        else:
            raise SystemExit(f'unknown gold kind {kind!r} in: {raw}')
        lines += [f'  g-{nm} : {ty}', f'  g-{nm} = [{", ".join(items)}]', '']
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: gen_gold.py <Chapter>   e.g. gen_gold.py GuardRail')
    name = sys.argv[1]
    text = gold_chapter(name, build_and_run(name))
    out = ROOT / 'gold' / f'{name}Gold.codex'
    out.write_text(text)
    print(f'{out.relative_to(ROOT)}  ({len(text.splitlines())} lines)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
