// Generate gold/BlitGold.codex from the FROZEN original blitter.
//
//   node harness/gen_blit_gold.js
//
// THE ORACLE HERE IS JAVASCRIPT. Every other gold in this repository comes from
// importing a real zig game module; these numbers come from the browser half,
// because the browser half is where the shading recipe and the visibility
// thresholds actually live. It is the same arrangement and the same rule: the
// oracle is the thing that is authoritative today, and it is imported rather
// than transcribed.
//
// IT READS `HISTORICAL_WASM_ROOT/blitter.js`, NOT OUR FORK -- see
// harness/blitter_oracle.js, which does the reading. The fork used to hold the
// recipe and this file lifted it from there by name; the fork has since handed
// the recipe to Codex, and an oracle that empties out when its subject does was
// never an oracle at all.
//
// The INPUT tables are printed too, and the check maps over those, so there is
// exactly one copy of every input rather than two kept in step by hand.

const fs = require('fs');
const path = require('path');
const F = require('./blitter_oracle.js');

const COLORS = [0x000000, 0x010203, 0x4a8f43, 0x7f7f7f, 0x808080, 0xc0ffee,
                0xff0000, 0x00ff00, 0x0000ff, 0xfedcba, 0xffffff];
const FACTORS = [0.0, 0.25, 0.6, 0.75, 1.0, 1.25, 1.6, 2.0, 4.0];
const STRENGTHS = [0.0, 0.01, 0.25, 0.5, 0.75, 1.0];
const RADII = [0.0, 0.1, 0.49, 0.5, 0.51, 1.0, 40.0];
const ALPHAS = [0.0, 0.01, 0.019, 0.02, 0.021, 0.5, 1.0];
const WIDTHS = [[0, 0], [0, 0.5], [0, 0.999], [0, 1], [0, 1.5], [10, 10.5], [10, 40]];

const reals = (xs) => '[' + xs.map((x) => (Number.isInteger(x) ? x.toFixed(1) : String(x))).join(', ') + ']';
const ints = (xs) => '[' + xs.join(', ') + ']';
const bools = (xs) => '[' + xs.map((b) => (b ? 'True' : 'False')).join(', ') + ']';

const shadeIn = [], shadeF = [], shadeOut = [];
for (const c of COLORS) for (const f of FACTORS) { shadeIn.push(c); shadeF.push(f); shadeOut.push(F.shadeColor(c, f)); }

const crownC = [], crownS = [], crownOut = [];
for (const c of COLORS) for (const s of STRENGTHS) {
  crownC.push(c); crownS.push(s);
  for (const [, col] of F.widthShadeStops(c, s)) crownOut.push(col);
}

const discR = [], discA = [], discOut = [];
for (const r of RADII) for (const a of ALPHAS) { discR.push(r); discA.push(a); discOut.push(F.discIsVisible(r, a)); }

const out = [];
out.push('Chapter: BlitGold', '');
out.push(' GENERATED by harness/gen_blit_gold.js from HISTORICAL_WASM_ROOT/blitter.js.');
out.push(' Every value here came from the frozen original browser half, unmodified.');
out.push(' Do not edit: the next harness run overwrites this file.', '');
out.push(' We say:', '', 'Section: Gold', '');
out.push(`  g-blit-shade-c : List Integer`, `  g-blit-shade-c = ${ints(shadeIn)}`, '');
out.push(`  g-blit-shade-f : List Real`, `  g-blit-shade-f = ${reals(shadeF)}`, '');
out.push(`  g-blit-shade : List Integer`, `  g-blit-shade = ${ints(shadeOut)}`, '');
out.push(`  g-blit-crown-c : List Integer`, `  g-blit-crown-c = ${ints(crownC)}`, '');
out.push(`  g-blit-crown-s : List Real`, `  g-blit-crown-s = ${reals(crownS)}`, '');
out.push(`  g-blit-crown : List Integer`, `  g-blit-crown = ${ints(crownOut)}`, '');
out.push(`  g-blit-disc-r : List Real`, `  g-blit-disc-r = ${reals(discR)}`, '');
out.push(`  g-blit-disc-a : List Real`, `  g-blit-disc-a = ${reals(discA)}`, '');
out.push(`  g-blit-disc : List Boolean`, `  g-blit-disc = ${bools(discOut)}`, '');
out.push(`  g-blit-radial-r : List Real`, `  g-blit-radial-r = ${reals(RADII)}`, '');
out.push(`  g-blit-radial : List Boolean`, `  g-blit-radial = ${bools(RADII.map(F.radialIsVisible))}`, '');
out.push(`  g-blit-width-lo : List Real`, `  g-blit-width-lo = ${reals(WIDTHS.map((w) => w[0]))}`, '');
out.push(`  g-blit-width-hi : List Real`, `  g-blit-width-hi = ${reals(WIDTHS.map((w) => w[1]))}`, '');
out.push(`  g-blit-flat : List Boolean`, `  g-blit-flat = ${bools(WIDTHS.map(([a, b]) => F.tooNarrowToShade(a, b)))}`, '');
out.push('Page 1', '');
const dest = path.join(__dirname, '..', 'gold', 'BlitGold.codex');
fs.writeFileSync(dest, out.join('\n'));
console.log(`gold/BlitGold.codex  (${out.length} lines)`);
