#!/usr/bin/env python3
"""Build a module's zig probe, run it, and write its answers as a Codex chapter.

The gold is REGENERATED from the hand-written zig on every run rather than
checked in. A checked-in gold file is a second copy of the oracle, and a second
copy is a thing that can quietly disagree with the first -- which is the failure
this port exists to detect, so it must not be possible to introduce it here.

Takes the CHAPTER name -- `Pond`, `GuardRail` -- and derives the rest, so a
module is named once. The probe is snake_case, matching the game file it imports
(`GuardRail` -> `probe/probe_guard_rail.zig`, beside `wasm/guard_rail.zig`); the
gold chapter is the name with `Gold` appended.

Reads `<kind> <name> <values...>` lines from the probe (kinds R, I, B; see
probe/probe_pond.zig) and emits one Codex binding per line, named `g-<name>`.

Real literals: zig's {d} prints the shortest round-tripping form, so `3` and
`0.9` arrive as text that already carries the f32 exactly. Codex wants a decimal
point on every Real, and exponent forms are expanded rather than passed through,
because a literal is the one place a port cannot afford a parse it has not seen.
"""

import decimal
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
ZIG = pathlib.Path.home() / 'zig-0.16.0' / 'zig'


def snake(chapter):
    """`GuardRail` -> `guard_rail`; a single-word chapter is unchanged but lowered."""
    return re.sub(r'(?<!^)(?=[A-Z])', '_', chapter).lower()


def real_literal(tok):
    """A Codex Real literal for one token of zig {d} output."""
    if 'e' in tok or 'E' in tok:
        tok = format(decimal.Decimal(tok), 'f')
    return tok if '.' in tok else tok + '.0'


def build_and_run(chapter):
    """Compile the probe beside its source, so the wasm/ symlink resolves."""
    probe = ROOT / 'probe'
    src = f'probe_{snake(chapter)}.zig'
    if not (probe / src).is_file():
        raise SystemExit(f'no probe/{src}')
    subprocess.run([str(ZIG), 'build-exe', src, '-O', 'ReleaseFast'],
                   cwd=probe, check=True)
    # The probes write to stderr: zig 0.16 removed std.io.getStdOut() and
    # std.debug.print is what the rest of this harness uses.
    out = subprocess.run([f'./probe_{snake(chapter)}'], cwd=probe,
                         capture_output=True, text=True, check=True)
    return out.stderr


def gold_chapter(chapter, gold_text):
    name = chapter + 'Gold'
    lines = [f'Chapter: {name}', '',
             f' GENERATED by harness/gen_gold.py from probe/probe_{snake(chapter)}.zig.',
             ' Every value here came from importing the real game module unmodified.',
             ' Do not edit: the next harness run overwrites this file.', '',
             ' We say:', '', 'Section: Gold', '']
    for raw in gold_text.splitlines():
        if not raw.strip():
            continue
        kind, nm, *vals = raw.split()
        if kind == 'R':
            ty, items = 'List Real', [real_literal(v) for v in vals]
        elif kind == 'I':
            ty, items = 'List Integer', vals
        elif kind == 'B':
            ty, items = 'List Boolean', ['True' if v == '1' else 'False' for v in vals]
        else:
            raise SystemExit(f'unknown gold kind {kind!r} in: {raw}')
        lines += [f'  g-{nm} : {ty}', f'  g-{nm} = [{", ".join(items)}]', '']
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: gen_gold.py <Chapter>   e.g. gen_gold.py GuardRail')
    name = sys.argv[1]
    text = gold_chapter(name, build_and_run(name))
    out = ROOT / 'gold' / f'{name}Gold.codex'
    out.write_text(text)
    print(f'{out.relative_to(ROOT)}  ({len(text.splitlines())} lines)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
